### ISSUE TITLE
I cannot install the gem.

### ISSUE THREAD

**Issue by samuraraujo** [ruby-rdf/linkeddata#10]
gem install linkeddata
ERROR:  Could not find a valid gem 'rdf' (>= 2.2.8, ~> 2.2) in any repository
ERROR:  Possible alternatives: rdf

rvm 1.29.2
Ruby 2.3.3
linux ubuntu

Any idea what may cause the issue?

**Comment by gkellogg** [comment]
Sorry, completed work and froze 2.2.8 last Thursday, but failed to actually release the gem; it's done now.
