### ISSUE TITLE
Installing linkeddata gem fails with undefined class/module YAML::Syck::DefaultKey

### ISSUE THREAD

**Issue by ijdickinson** [ruby-rdf/linkeddata#3]
Using jruby-1.6.3 (but it also happens with .1 and .2), I tried:

    ian@rowan-15 $ gem install linkeddata
    ERROR:  While executing gem ... (ArgumentError)
       undefined class/module YAML::Syck::DefaultKey

Googling around, I see that other gems have been having the same problem, but it's not clear to me what, if any, workaround I can apply locally. Suggestions welcome!

Thanks,
Ian

**Comment by gkellogg** [comment]
Presume this has been resolved.
