### ISSUE TITLE
Build fails on Ruby 1.9.3

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/linkeddata#6]
The `[.travis.yml](https://github.com/ruby-rdf/linkeddata/blob/develop/.travis.yml#L6)` for this suggests that Ruby 1.9.3 is supported, but the latest `rdf-tabular` requires Ruby 2.

I'm dropping support for 1.9.3 in ActiveTriples/ActiveTriples in response to this, but wanted to make you aware of the issue.

**Comment by gkellogg** [comment]
Good point; supporting < 2.0 in rdf-tabular is problematic, but not impossible. ref-reasoner will not finish tests on Travis, but it works.

The time's probably come to update minimum requirements to 2.0 across the board.

**Comment by gkellogg** [comment]
Fixed/released in 38918d97a7b42869a31812906e48c28fff9998e9 v 1.1.11.1
