### ISSUE TITLE
Update documentation to note inclusion of rdf-vocab

### ISSUE THREAD

**Issue by darrenleeweber** [ruby-rdf/linkeddata#7]
The README.md doesn't yet note the inclusion of rdf-vocab, i.e.
https://github.com/ruby-rdf/linkeddata/blob/develop/linkeddata.gemspec#L43

**Comment by gkellogg** [comment]
Indeed, I thought I had added that, but I guess not. I'll update that and regenerate the docs, although it shouldn't require an update to the gem itself.
